In [1]:
import pandas as pd

# Path to the .dta file
file_path = '/Users/vincent.k.kapp/Data-Analysis-with-LLM-13/experiment/data/usa_00013.dta'

# Read the .dta file
df = pd.read_stata(file_path)

# Display the DataFrame
print(df.columns)

Index(['year', 'datanum', 'serial', 'hhwt', 'region', 'metro', 'gq', 'pernum',
       'perwt', 'famsize', 'nchild', 'nchlt5', 'eldch', 'yngch', 'nsibs',
       'sex', 'age', 'marst', 'birthyr', 'marrno', 'marrinyr', 'yrmarr',
       'fertyr', 'race', 'raced', 'hispan', 'hispand', 'bpl', 'bpld',
       'ancestr1', 'ancestr1d', 'citizen', 'yrnatur', 'yrimmig', 'yrsusa1',
       'speakeng', 'racamind', 'racasian', 'racblk', 'racpacis', 'racwht',
       'racother', 'school', 'educ', 'educd', 'gradeatt', 'gradeattd',
       'schltype', 'degfield', 'degfieldd', 'degfield2', 'degfield2d',
       'empstat', 'empstatd', 'labforce', 'occ', 'occ1990', 'occ2010', 'ind',
       'ind1990', 'classwkr', 'classwkrd', 'occsoc', 'indnaics', 'wkswork2',
       'uhrswork', 'workedyr', 'incwage', 'prent', 'edscor90', 'vetstat',
       'vetstatd'],
      dtype='object')

In [16]:
#len(df.columns)
#df.shape[1]
df.columns.tolist()

['year',
 'datanum',
 'serial',
 'hhwt',
 'region',
 'metro',
 'gq',
 'pernum',
 'perwt',
 'famsize',
 'nchild',
 'nchlt5',
 'eldch',
 'yngch',
 'nsibs',
 'sex',
 'age',
 'marst',
 'birthyr',
 'marrno',
 'marrinyr',
 'yrmarr',
 'fertyr',
 'race',
 'raced',
 'hispan',
 'hispand',
 'bpl',
 'bpld',
 'ancestr1',
 'ancestr1d',
 'citizen',
 'yrnatur',
 'yrimmig',
 'yrsusa1',
 'speakeng',
 'racamind',
 'racasian',
 'racblk',
 'racpacis',
 'racwht',
 'racother',
 'school',
 'educ',
 'educd',
 'gradeatt',
 'gradeattd',
 'schltype',
 'degfield',
 'degfieldd',
 'degfield2',
 'degfield2d',
 'empstat',
 'empstatd',
 'labforce',
 'occ',
 'occ1990',
 'occ2010',
 'ind',
 'ind1990',
 'classwkr',
 'classwkrd',
 'occsoc',
 'indnaics',
 'wkswork2',
 'uhrswork',
 'workedyr',
 'incwage',
 'prent',
 'edscor90',
 'vetstat',
 'vetstatd']

In [17]:
def rename_columns(df):
    """
    Rename columns to more descriptive, standardized names.
    
    Args:
        df (pandas.DataFrame): Input dataframe to rename columns
    
    Returns:
        pandas.DataFrame: Dataframe with renamed columns
    """
    # Create a comprehensive mapping dictionary
    column_mapping = {
                        # Demographic
                        'sex': 'sex',
                        'age': 'age',
                        'birthyr': 'year_of_birth',
                        'race': 'race',
                        'raced': 'detailed_race',
                        'hispan': 'hispanic_origin',
                        'hispand': 'detailed_hispanic_origin',
                        'bpl': 'birthplace',
                        'bpld': 'detailed_birthplace',
                        'ancestr1': 'first_ancestry',
                        'ancestr1d': 'detailed_first_ancestry',
                        'citizen': 'citizenship_status',
                        'yrnatur': 'year_of_naturalization',
                        'yrimmig': 'year_of_immigration',
                        'yrsusa1': 'years_in_usa',
                        'speakeng': 'english_proficiency',
                        'racamind': 'american_indian_race',
                        'racasian': 'asian_race',
                        'racblk': 'black_race',
                        'racpacis': 'pacific_islander_race',
                        'racwht': 'white_race',
                        'racother': 'other_race',

                        # Household
                        'nchlt5': 'child_age_leq_4',
                        'famsize': 'family_size',
                        'nchild': 'number_of_children',
                        'eldch': 'age_of_eldest_child',
                        'yngch': 'age_of_youngest_child',
                        'nsibs': 'number_of_siblings',
                        'prent': 'parent_presence',
                        'hhwt': 'household_weight',
                        'metro': 'metropolitan_status',
                        'region': 'us_census_region',
                        'gq': 'group_quarters_status',

                        # Marital and Fertility
                        'marst': 'marital_status',
                        'marrno': 'number_of_marriages',
                        'marrinyr': 'married_within_year',
                        'yrmarr': 'year_of_marriage',
                        'fertyr': 'fertility_year',

                        # Education
                        'school': 'school_attendance',
                        'educ': 'education',
                        'educd': 'detailed_education',
                        'gradeatt': 'grade_attended',
                        'gradeattd': 'detailed_grade_attended',
                        'schltype': 'school_type',
                        'degfield': 'degree_field',
                        'degfieldd': 'detailed_degree_field',
                        'degfield2': 'second_degree_field',
                        'degfield2d': 'detailed_second_degree_field',
                        'edscor90': 'education_score_1990',

                        # Employment
                        'empstat': 'employment_status',
                        'empstatd': 'detailed_employment_status',
                        'labforce': 'labour_force_participation',
                        'occ': 'occupation',
                        'occ1990': 'occupation_1990_classification',
                        'occ2010': 'occupation_2010_classification',
                        'ind': 'industry',
                        'ind1990': 'industry_1990_classification',
                        'classwkr': 'class_of_worker',
                        'classwkrd': 'detailed_class_of_worker',
                        'occsoc': 'soc_occupation',
                        'indnaics': 'naics_industry',
                        'wkswork2': 'weeks_worked',
                        'uhrswork': 'usual_hours_worked',
                        'workedyr': 'worked_last_year',
                        'incwage': 'wage_income',

                        # Survey Metadata
                        'year': 'survey_year',
                        'datanum': 'dataset_number',
                        'serial': 'household_serial_number',
                        'pernum': 'person_number_within_household',
                        'perwt': 'person_weight',

                        # Veteran Status
                        'vetstat': 'veteran_status',
                        'vetstatd': 'detailed_veteran_status'
                    }
    
    # Rename the columns
    df_renamed = df.rename(columns=column_mapping)
    
    return df_renamed

# Call the function and print the result
df_renamed = rename_columns(df)
print(df_renamed)

        survey_year  dataset_number  household_serial_number  \
0              2016               1                      1.0
1              2016               1                      1.0
2              2016               1                      2.0
3              2016               1                      3.0
4              2016               1                      3.0
...             ...             ...                      ...
3156482        2016               1                1380230.0
3156483        2016               1                1380230.0
3156484        2016               1                1380231.0
3156485        2016               1                1380232.0
3156486        2016               1                1380233.0

         household_weight         us_census_region  \
0                    97.0  East South Central Div.
1                    97.0  East South Central Div.
2                    95.0  East South Central Div.
3                   159.0  East South Central Div.
4                   159.0  East South Central Div.
...                   ...                      ...
3156482             181.0        Mountain Division
3156483             181.0        Mountain Division
3156484              34.0        Mountain Division
3156485             314.0        Mountain Division
3156486             135.0        Mountain Division

                             metropolitan_status  \
0                              Not in metro area
1                              Not in metro area
2        Central / Principal city status unknown
3        Central / Principal city status unknown
4        Central / Principal city status unknown
...                                          ...
3156482                         Not identifiable
3156483                         Not identifiable
3156484                        Not in metro area
3156485                        Not in metro area
3156486                         Not identifiable

                    group_quarters_status  person_number_within_household  \
0        Households under 1970 definition                               1
1        Households under 1970 definition                               2
2        Households under 1970 definition                               1
3        Households under 1970 definition                               1
4        Households under 1970 definition                               2
...                                   ...                             ...
3156482  Households under 1970 definition                               1
3156483  Households under 1970 definition                               2
3156484      Group quarters--Institutions                               1
3156485              Other group quarters                               1
3156486  Households under 1970 definition                               1

         person_weight               family_size  ... soc_occupation  \
0                 98.0  2 family members present  ...              0
1                 89.0  2 family members present  ...              0
2                 95.0   1 family member present  ...         436010
3                160.0                         4  ...         173020
4                154.0                         4  ...              0
...                ...                       ...  ...            ...
3156482          181.0  2 family members present  ...              0
3156483          208.0  2 family members present  ...              0
3156484           34.0   1 family member present  ...              0
3156485          314.0   1 family member present  ...         412031
3156486          135.0   1 family member present  ...              0

        naics_industry weeks_worked usual_hours_worked worked_last_year  \
0                    0          N/A                N/A               No
1                    0          N/A                N/A               No
2                  622  50-52 weeks                 40              Yes
3                 5413  50-52 weeks                 40              Yes
4                    0          N/A                N/A               No
...                ...          ...                ...              ...
3156482              0          N/A                N/A               No
3156483              0          N/A                N/A               No
3156484              0          N/A                N/A               No
3156485          4441Z  50-52 weeks                 40              Yes
3156486              0          N/A                N/A               No

        wage_income parent_presence education_score_1990  veteran_status  \
0                 0             0.0                999.9   Not a veteran
1                 0             0.0                999.9   Not a veteran
2             27300            46.1                 60.4   Not a veteran
3             65000            47.7                 70.2   Not a veteran
4                 0             0.0                999.9   Not a veteran
...             ...             ...                  ...             ...
3156482           0             0.0                999.9         Veteran
3156483           0             0.0                999.9   Not a veteran
3156484           0             0.0                999.9   Not a veteran
3156485       16400            33.6                 54.1         Veteran
3156486           0             0.0                999.9   Not a veteran

                                 detailed_veteran_status
0                                    No military service
1                                    No military service
2                                    No military service
3           Training for Reserves or National Guard only
4                                    No military service
...                                                  ...
3156482                                          Veteran
3156483                              No military service
3156484                              No military service
3156485                                          Veteran
3156486                              No military service

[3156487 rows x 72 columns]

In [18]:
print(df_renamed.columns)

Index(['survey_year', 'dataset_number', 'household_serial_number',
       'household_weight', 'us_census_region', 'metropolitan_status',
       'group_quarters_status', 'person_number_within_household',
       'person_weight', 'family_size', 'number_of_children', 'child_age_leq_4',
       'age_of_eldest_child', 'age_of_youngest_child', 'number_of_siblings',
       'sex', 'age', 'marital_status', 'year_of_birth', 'number_of_marriages',
       'married_within_year', 'year_of_marriage', 'fertility_year', 'race',
       'detailed_race', 'hispanic_origin', 'detailed_hispanic_origin',
       'birthplace', 'detailed_birthplace', 'first_ancestry',
       'detailed_first_ancestry', 'citizenship_status',
       'year_of_naturalization', 'year_of_immigration', 'years_in_usa',
       'english_proficiency', 'american_indian_race', 'asian_race',
       'black_race', 'pacific_islander_race', 'white_race', 'other_race',
       'school_attendance', 'education', 'detailed_education',
       'grade_attended', 'detailed_grade_attended', 'school_type',
       'degree_field', 'detailed_degree_field', 'second_degree_field',
       'detailed_second_degree_field', 'employment_status',
       'detailed_employment_status', 'labour_force_participation',
       'occupation', 'occupation_1990_classification',
       'occupation_2010_classification', 'industry',
       'industry_1990_classification', 'class_of_worker',
       'detailed_class_of_worker', 'soc_occupation', 'naics_industry',
       'weeks_worked', 'usual_hours_worked', 'worked_last_year', 'wage_income',
       'parent_presence', 'education_score_1990', 'veteran_status',
       'detailed_veteran_status'],
      dtype='object')

In [19]:
  print(df_renamed.head())

  survey_year  dataset_number  household_serial_number  household_weight  \
0        2016               1                      1.0              97.0
1        2016               1                      1.0              97.0
2        2016               1                      2.0              95.0
3        2016               1                      3.0             159.0
4        2016               1                      3.0             159.0

          us_census_region                      metropolitan_status  \
0  East South Central Div.                        Not in metro area
1  East South Central Div.                        Not in metro area
2  East South Central Div.  Central / Principal city status unknown
3  East South Central Div.  Central / Principal city status unknown
4  East South Central Div.  Central / Principal city status unknown

              group_quarters_status  person_number_within_household  \
0  Households under 1970 definition                               1
1  Households under 1970 definition                               2
2  Households under 1970 definition                               1
3  Households under 1970 definition                               1
4  Households under 1970 definition                               2

   person_weight               family_size  ... soc_occupation naics_industry  \
0           98.0  2 family members present  ...              0              0
1           89.0  2 family members present  ...              0              0
2           95.0   1 family member present  ...         436010            622
3          160.0                         4  ...         173020           5413
4          154.0                         4  ...              0              0

  weeks_worked usual_hours_worked worked_last_year wage_income  \
0          N/A                N/A               No           0
1          N/A                N/A               No           0
2  50-52 weeks                 40              Yes       27300
3  50-52 weeks                 40              Yes       65000
4          N/A                N/A               No           0

  parent_presence education_score_1990  veteran_status  \
0             0.0                999.9   Not a veteran
1             0.0                999.9   Not a veteran
2            46.1                 60.4   Not a veteran
3            47.7                 70.2   Not a veteran
4             0.0                999.9   Not a veteran

                           detailed_veteran_status
0                              No military service
1                              No military service
2                              No military service
3     Training for Reserves or National Guard only
4                              No military service

[5 rows x 72 columns]

In [25]:
# Export the DataFrame to a CSV file
output_path = '/Users/vincent.k.kapp/Data-Analysis-with-LLM-13/experiment/data/output_file.csv'
df_renamed.to_csv(output_path, index=False)

In [27]:
# Get unique values for each column
unique_values = {col: df_renamed[col].unique() for col in df_renamed.columns}

# Display the unique values for each column
for col, values in unique_values.items():
    print(f"Column: {col}")
    print(values)
    print("\n")

Column: survey_year
['2016']
Categories (1, object): ['2016']


Column: dataset_number
[1]


Column: household_serial_number
[1.000000e+00 2.000000e+00 3.000000e+00 ... 1.380231e+06 1.380232e+06
 1.380233e+06]


Column: household_weight
[9.700e+01 9.500e+01 1.590e+02 1.220e+02 2.000e+01 2.260e+02 1.500e+01
 2.250e+02 1.510e+02 1.800e+01 1.110e+02 2.040e+02 5.900e+01 8.600e+01
 1.000e+01 7.800e+01 7.100e+01 5.000e+01 2.700e+01 3.100e+01 4.200e+01
 8.500e+01 7.300e+01 7.500e+01 2.900e+01 2.140e+02 4.800e+01 2.460e+02
 1.730e+02 6.200e+01 1.400e+01 7.700e+01 7.400e+01 4.900e+01 2.770e+02
 1.010e+02 2.570e+02 2.010e+02 6.100e+01 4.600e+01 1.230e+02 1.050e+02
 1.090e+02 6.500e+01 8.300e+01 7.600e+01 8.700e+01 1.100e+01 4.400e+01
 9.400e+01 1.170e+02 1.570e+02 1.210e+02 1.450e+02 9.100e+01 1.200e+02
 7.900e+01 3.000e+01 5.200e+01 1.280e+02 2.200e+01 9.200e+01 3.550e+02
 8.800e+01 4.100e+01 2.100e+01 1.540e+02 5.600e+01 6.700e+01 9.000e+01
 6.300e+01 3.010e+02 2.500e+01 1.420e+02 1.890e+02 1.430e+02 3.400e+01
 6.400e+01 2.600e+01 6.600e+01 6.900e+01 5.500e+01 3.510e+02 1.480e+02
 1.120e+02 1.900e+01 1.490e+02 4.000e+01 1.180e+02 2.300e+01 1.000e+02
 9.300e+01 8.900e+01 8.100e+01 2.470e+02 8.000e+01 2.810e+02 1.990e+02
 5.100e+01 1.330e+02 2.280e+02 3.300e+01 1.410e+02 1.080e+02 9.000e+00
 5.100e+02 2.200e+02 1.560e+02 5.800e+01 1.030e+02 9.900e+01 1.740e+02
 2.300e+02 5.700e+01 1.100e+02 1.300e+01 8.400e+01 3.600e+01 3.200e+01
 2.150e+02 1.440e+02 1.850e+02 6.800e+01 2.640e+02 1.600e+02 1.980e+02
 2.420e+02 1.600e+01 2.240e+02 3.500e+01 4.330e+02 1.060e+02 9.800e+01
 1.700e+01 5.000e+00 4.840e+02 6.000e+01 1.140e+02 3.900e+01 1.070e+02
 4.300e+01 1.580e+02 1.310e+02 3.560e+02 1.200e+01 1.400e+02 5.400e+01
 3.800e+01 1.250e+02 2.320e+02 2.510e+02 1.260e+02 3.830e+02 1.320e+02
 1.160e+02 1.350e+02 2.560e+02 1.660e+02 7.000e+01 1.040e+02 2.900e+02
 8.200e+01 9.600e+01 6.530e+02 2.230e+02 3.700e+01 3.150e+02 1.190e+02
 5.090e+02 7.200e+01 1.520e+02 3.350e+02 4.700e+01 2.800e+01 6.000e+00
 1.550e+02 1.270e+02 4.290e+02 1.690e+02 3.270e+02 1.300e+02 1.240e+02
 5.010e+02 4.000e+00 1.830e+02 1.710e+02 1.910e+02 7.000e+00 2.210e+02
 2.400e+01 5.300e+01 2.650e+02 3.380e+02 2.500e+02 1.860e+02 2.350e+02
 1.630e+02 1.920e+02 1.720e+02 2.050e+02 1.750e+02 4.500e+01 1.640e+02
 1.150e+02 2.830e+02 1.020e+02 2.430e+02 2.000e+00 2.030e+02 1.130e+02
 2.330e+02 2.840e+02 2.930e+02 2.880e+02 1.390e+02 2.100e+02 2.720e+02
 6.450e+02 1.610e+02 1.840e+02 1.670e+02 3.190e+02 2.170e+02 1.970e+02
 2.700e+02 1.900e+02 1.530e+02 3.370e+02 2.130e+02 1.760e+02 1.800e+02
 1.810e+02 1.370e+02 3.020e+02 1.380e+02 4.240e+02 2.160e+02 1.340e+02
 1.880e+02 1.780e+02 3.940e+02 1.460e+02 3.610e+02 1.820e+02 3.300e+02
 1.500e+02 5.240e+02 3.950e+02 2.290e+02 4.010e+02 1.360e+02 3.260e+02
 2.870e+02 1.700e+02 2.490e+02 1.790e+02 2.620e+02 4.730e+02 8.000e+00
 4.040e+02 6.950e+02 3.900e+02 1.930e+02 1.950e+02 3.780e+02 1.650e+02
 1.290e+02 2.690e+02 2.450e+02 2.190e+02 2.220e+02 3.000e+00 1.470e+02
 2.020e+02 2.400e+02 1.770e+02 3.540e+02 5.580e+02 2.310e+02 2.440e+02
 3.230e+02 3.030e+02 2.750e+02 4.190e+02 3.420e+02 4.020e+02 1.870e+02
 3.330e+02 3.450e+02 1.620e+02 2.590e+02 3.880e+02 5.040e+02 3.120e+02
 2.680e+02 4.220e+02 6.030e+02 2.850e+02 4.380e+02 2.090e+02 3.140e+02
 2.790e+02 4.970e+02 4.720e+02 2.340e+02 4.410e+02 2.550e+02 3.700e+02
 2.360e+02 2.120e+02 7.660e+02 2.960e+02 1.680e+02 5.690e+02 2.270e+02
 2.000e+02 3.250e+02 1.940e+02 4.140e+02 2.580e+02 3.340e+02 5.530e+02
 2.390e+02 2.760e+02 4.080e+02 3.720e+02 3.110e+02 2.820e+02 2.410e+02
 4.110e+02 3.580e+02 3.660e+02 3.870e+02 4.460e+02 2.860e+02 2.740e+02
 3.750e+02 3.240e+02 2.540e+02 2.660e+02 3.730e+02 3.400e+02 8.440e+02
 2.600e+02 3.810e+02 2.060e+02 2.730e+02 2.990e+02 2.630e+02 3.310e+02
 5.170e+02 2.080e+02 2.780e+02 3.570e+02 2.370e+02 3.800e+02 3.290e+02
 3.220e+02 2.890e+02 3.920e+02 4.570e+02 1.000e+00 7.670e+02 5.140e+02
 5.050e+02 3.360e+02 2.070e+02 2.910e+02 3.760e+02 4.540e+02 5.460e+02
 3.130e+02 3.050e+02 4.920e+02 2.970e+02 3.390e+02 6.060e+02 3.680e+02
 3.690e+02 3.040e+02 5.220e+02 3.470e+02 2.520e+02 3.740e+02 4.610e+02
 3.100e+02 3.200e+02 4.900e+02 5.380e+02 3.170e+02 4.210e+02 3.710e+02
 3.410e+02 2.530e+02 3.480e+02 2.110e+02 3.440e+02 4.050e+02 3.840e+02
 4.200e+02 3.160e+02 2.610e+02 4.880e+02 3.670e+02 3.180e+02 4.310e+02
 4.400e+02 4.760e+02 2.980e+02 3.910e+02 3.210e+02 4.830e+02 3.000e+02
 3.890e+02 3.080e+02 4.250e+02 2.950e+02 2.670e+02 4.590e+02 5.130e+02
 3.520e+02 3.640e+02 5.410e+02 2.920e+02 4.360e+02 4.150e+02 3.060e+02
 2.800e+02 2.480e+02 5.340e+02 3.770e+02 2.180e+02 4.510e+02 7.010e+02
 3.930e+02 6.040e+02 5.640e+02 4.430e+02 4.890e+02 3.820e+02 4.520e+02
 5.510e+02 1.960e+02 4.930e+02 6.750e+02 8.830e+02 3.990e+02 5.920e+02
 5.200e+02 4.100e+02 3.970e+02 5.970e+02 4.060e+02 2.940e+02 4.500e+02
 4.370e+02 7.980e+02 4.260e+02 4.070e+02 3.650e+02 4.470e+02 4.850e+02
 4.670e+02 3.600e+02 5.420e+02 4.870e+02 4.440e+02 2.380e+02 4.990e+02
 4.530e+02 4.280e+02 5.960e+02 3.630e+02 6.780e+02 3.090e+02 4.640e+02
 4.750e+02 5.310e+02 4.550e+02 7.160e+02 4.320e+02 4.230e+02 4.820e+02
 5.180e+02 4.740e+02 3.850e+02 4.350e+02 6.690e+02 4.160e+02 3.860e+02
 3.500e+02 3.460e+02 3.530e+02 5.350e+02 4.300e+02 5.150e+02 8.180e+02
 4.980e+02 9.930e+02 6.500e+02 5.600e+02 4.580e+02 4.390e+02 5.540e+02
 3.430e+02 5.280e+02 4.620e+02 5.070e+02 5.120e+02 5.770e+02 3.620e+02
 6.940e+02 5.020e+02 4.690e+02 3.490e+02 7.000e+02 3.960e+02 3.320e+02
 2.710e+02 7.280e+02 6.170e+02 3.790e+02 5.160e+02 5.190e+02 4.030e+02
 4.270e+02 6.070e+02 3.590e+02 3.280e+02 5.980e+02 6.270e+02 6.210e+02
 4.560e+02 5.400e+02 1.000e+03 6.100e+02 4.650e+02 4.000e+02 8.840e+02
 6.670e+02 6.230e+02 5.110e+02 6.890e+02 5.930e+02 5.620e+02 5.670e+02
 7.020e+02 5.870e+02 8.210e+02 5.610e+02 6.010e+02 4.790e+02 1.014e+03
 7.320e+02 6.610e+02 5.810e+02 6.520e+02 6.280e+02 5.940e+02 4.090e+02
 7.920e+02 6.580e+02 8.080e+02 4.450e+02 6.320e+02 7.530e+02 5.860e+02
 6.470e+02 6.790e+02 9.860e+02 3.070e+02 3.980e+02 4.490e+02 4.120e+02
 6.350e+02 6.310e+02 5.270e+02 4.130e+02 6.370e+02 5.470e+02 6.650e+02
 5.730e+02 4.340e+02 4.660e+02 4.170e+02 4.910e+02 5.320e+02 4.680e+02
 4.780e+02 4.700e+02 5.300e+02 5.030e+02 5.450e+02 5.080e+02 4.960e+02
 7.080e+02 5.910e+02 6.660e+02 5.550e+02 6.050e+02 5.790e+02 4.940e+02
 6.730e+02 4.800e+02 5.390e+02 7.220e+02 7.240e+02 6.200e+02 5.500e+02
 5.520e+02 4.480e+02 6.120e+02 6.900e+02 5.760e+02 4.860e+02 4.950e+02
 4.180e+02 5.570e+02 5.840e+02 4.630e+02 5.950e+02 6.570e+02 4.710e+02
 5.000e+02 5.890e+02 5.440e+02 9.280e+02 6.260e+02 5.370e+02 8.280e+02
 6.560e+02 6.420e+02 6.340e+02 5.850e+02 1.150e+03 5.660e+02 1.151e+03
 5.360e+02 5.230e+02 6.020e+02 4.420e+02 5.490e+02 4.770e+02 1.027e+03
 9.680e+02 5.560e+02 7.340e+02 6.490e+02 6.860e+02 4.810e+02 6.760e+02
 6.540e+02 8.470e+02 5.720e+02 9.060e+02 4.600e+02 7.450e+02 6.440e+02
 5.590e+02 7.470e+02 6.080e+02 5.060e+02 5.260e+02 5.990e+02 1.072e+03
 7.600e+02 2.318e+03 8.610e+02 5.430e+02 5.250e+02 5.780e+02 8.300e+02
 5.290e+02 1.095e+03 6.820e+02 5.820e+02 7.210e+02 6.150e+02 5.680e+02
 1.002e+03 5.480e+02 5.650e+02 6.250e+02 5.210e+02 1.009e+03 7.960e+02
 6.090e+02 6.160e+02 7.150e+02 6.130e+02 9.390e+02 7.060e+02 7.880e+02
 5.330e+02 7.990e+02 6.630e+02 6.960e+02 6.880e+02 6.180e+02 6.400e+02
 7.110e+02 7.700e+02 6.710e+02 6.410e+02 6.140e+02 6.000e+02 7.770e+02
 9.740e+02 8.990e+02 8.630e+02 1.060e+03 6.740e+02 5.830e+02 7.720e+02
 8.740e+02 8.560e+02 6.680e+02 7.390e+02 7.350e+02 7.840e+02 6.360e+02
 9.570e+02 1.158e+03 6.190e+02 9.190e+02 6.390e+02 8.140e+02 7.230e+02
 6.970e+02 5.710e+02 8.250e+02 8.910e+02 7.550e+02 7.650e+02 8.070e+02
 5.800e+02 1.096e+03 6.110e+02 6.380e+02 5.880e+02 9.310e+02 6.810e+02
 5.900e+02 1.050e+03 7.630e+02 7.640e+02 6.700e+02 7.360e+02 6.990e+02
 7.130e+02 8.400e+02 1.025e+03 7.970e+02 8.800e+02 5.750e+02 7.620e+02
 1.110e+03 8.500e+02 8.090e+02 7.430e+02 9.620e+02 6.620e+02 8.060e+02
 8.030e+02 7.420e+02 6.480e+02 8.320e+02 7.190e+02 5.630e+02 1.118e+03
 6.430e+02 1.265e+03 8.790e+02 8.190e+02 7.830e+02 7.070e+02 6.240e+02
 7.950e+02 8.550e+02 7.780e+02 6.220e+02 1.040e+03 8.160e+02 7.690e+02
 9.480e+02 7.270e+02 7.040e+02 9.660e+02 1.176e+03 9.650e+02 8.130e+02
 1.287e+03 5.740e+02 8.360e+02 1.127e+03 9.080e+02 6.720e+02 6.300e+02
 7.140e+02 6.600e+02 9.180e+02 8.810e+02 6.840e+02 6.550e+02 1.010e+03
 7.330e+02 6.510e+02 1.028e+03 6.290e+02 7.180e+02 6.850e+02 6.640e+02
 7.370e+02 8.010e+02 1.197e+03 1.302e+03 5.700e+02 7.890e+02 6.460e+02
 8.640e+02 9.830e+02 7.610e+02 6.770e+02 7.460e+02 1.266e+03 7.410e+02
 7.680e+02 9.360e+02 7.300e+02 7.050e+02 1.410e+03 1.123e+03 1.124e+03
 1.504e+03 1.011e+03 8.220e+02 9.550e+02 9.870e+02 7.790e+02 8.620e+02
 8.170e+02 9.730e+02 7.100e+02 7.580e+02 7.400e+02 7.250e+02 7.260e+02
 7.200e+02 1.246e+03 1.035e+03 1.157e+03 8.230e+02 7.740e+02 1.464e+03
 1.149e+03 6.930e+02 7.810e+02 6.870e+02 9.120e+02 1.082e+03 1.245e+03
 6.330e+02 8.580e+02 1.432e+03 1.254e+03 8.940e+02 9.690e+02 1.294e+03
 1.347e+03 1.261e+03 1.008e+03 1.244e+03 7.120e+02 1.395e+03 6.920e+02
 1.056e+03 9.600e+02 1.140e+03 6.910e+02 8.460e+02 8.430e+02 7.590e+02
 9.540e+02 7.500e+02 6.590e+02 9.760e+02 7.170e+02 1.046e+03 7.290e+02
 6.980e+02 1.349e+03 8.930e+02 8.650e+02 7.520e+02 8.200e+02 7.510e+02
 1.083e+03 8.260e+02 1.184e+03 8.120e+02 9.110e+02 7.030e+02 9.580e+02
 8.710e+02 1.125e+03 8.960e+02 1.081e+03 7.820e+02 8.590e+02 8.730e+02
 7.930e+02 1.105e+03 7.540e+02 9.270e+02 9.640e+02 9.990e+02 8.570e+02
 1.394e+03 7.090e+02 9.010e+02 1.289e+03 1.746e+03 6.830e+02 7.760e+02
 6.800e+02 8.350e+02 9.100e+02 9.090e+02 8.410e+02 1.235e+03 9.810e+02
 8.540e+02 7.710e+02 7.310e+02 9.560e+02 9.220e+02 7.380e+02 7.480e+02
 1.148e+03 8.770e+02 9.140e+02 8.110e+02 9.070e+02 8.020e+02 8.330e+02
 8.310e+02 8.150e+02 9.470e+02 1.041e+03 8.980e+02 8.040e+02 1.117e+03
 9.780e+02 1.159e+03 8.050e+02 7.490e+02 8.100e+02 1.007e+03 1.219e+03
 8.480e+02 8.510e+02 9.300e+02 9.130e+02 7.800e+02 8.270e+02 9.230e+02
 8.890e+02 1.172e+03 1.300e+03 8.860e+02 8.950e+02 1.054e+03 9.490e+02
 1.021e+03 8.760e+02 8.530e+02 8.600e+02 1.114e+03 8.970e+02 8.240e+02
 7.850e+02 1.209e+03 1.214e+03 9.000e+02 9.630e+02 1.177e+03 1.074e+03
 9.210e+02 8.700e+02 1.360e+03 7.440e+02 8.920e+02]


Column: us_census_region
['East South Central Div.', 'Pacific Division', 'Mountain Division', 'West South Central Div.', 'New England Division', 'South Atlantic Division', 'East North Central Div.', 'West North Central Div.', 'Middle Atlantic Division']
Categories (9, object): ['New England Division' < 'Middle Atlantic Division' < 'East North Central Div.' < 'West North Central Div.' ... 'East South Central Div.' < 'West South Central Div.' < 'Mountain Division' < 'Pacific Division']


Column: metropolitan_status
['Not in metro area', 'Central / Principal city status unknown', 'Not identifiable', 'In metro area, outside central / principal city', 'In metro area, central / principal city']
Categories (5, object): ['Not identifiable' < 'Not in metro area' < 'In metro area, central / principal city' < 'In metro area, outside central / principal city' < 'Central / Principal city status unknown']


Column: group_quarters_status
['Households under 1970 definition', 'Group quarters--Institutions', 'Other group quarters', 'Additional households under 1990 definition', 'Additional households under 2000 definition']
Categories (5, object): ['Households under 1970 definition' < 'Additional households under 1990 definition' < 'Group quarters--Institutions' < 'Other group quarters' < 'Additional households under 2000 definition']


Column: person_number_within_household
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


Column: person_weight
[  98.   89.   95. ...  932. 1360.  971.]


Column: family_size
['2 family members present', '1 family member present', '4', '5', '3', ..., '14', '18', '17', '16', '20']
Length: 19
Categories (19, object): ['1 family member present' < '2 family members present' < '3' < '4' ... '16' < '17' < '18' < '20']


Column: number_of_children
['0 children present', '2', '3', '1 child present', '7', '4', '5', '6', '8', '9+']
Categories (10, object): ['0 children present' < '1 child present' < '2' < '3' ... '6' < '7' < '8' < '9+']


Column: child_age_leq_4
['No children under age 5', '1 child under age 5', '2', '3', '4', '5', '8', '6']
Categories (8, object): ['No children under age 5' < '1 child under age 5' < '2' < '3' < '4' < '5' < '6' < '8']


Column: age_of_eldest_child
['N/A', '20', '8', '15', '4', ..., '82', '79', '83', '86', '85']
Length: 89
Categories (89, object): ['Less than 1 year old' < '1' < '2' < '3' ... '86' < '88' < '89' < 'N/A']


Column: age_of_youngest_child
['N/A', '16', '1', '12', '4', ..., '82', '79', '83', '85', '86']
Length: 88
Categories (88, object): ['Less than 1 year old' < '1' < '2' < '3' ... '85' < '86' < '88' < 'N/A']


Column: number_of_siblings
['0 siblings', '1 sibling', '2 siblings', '6 siblings', '3 siblings', '4 siblings', '5 siblings', '7 siblings', '8 siblings', '9 or more siblings']
Categories (10, object): ['0 siblings' < '1 sibling' < '2 siblings' < '3 siblings' ... '6 siblings' < '7 siblings' < '8 siblings' < '9 or more siblings']


Column: sex
['Female', 'Male']
Categories (2, object): ['Male' < 'Female']


Column: age
['84', '78', '46', '52', '20', ..., '90 (90+ in 1980 and 1990)', '94', '92', '96', '95']
Length: 97
Categories (97, object): ['Less than 1 year old' < '1' < '2' < '3' ... '93' < '94' < '95' < '96']


Column: marital_status
['Married, spouse present', 'Divorced', 'Never married/single', 'Separated', 'Widowed', 'Married, spouse absent']
Categories (6, object): ['Married, spouse present' < 'Married, spouse absent' < 'Separated' < 'Divorced' < 'Widowed' < 'Never married/single']


Column: year_of_birth
[1932 1938 1970 1964 1996 2000 1950 1948 1952 1953 1991 1993 1981 1990
 2010 2015 2008 1979 2001 2004 1933 1980 2012 1944 1940 1986 1983 2003
 2005 2007 1963 1945 1971 1959 1992 1966 1967 1949 1923 1930 1947 1974
 1955 1941 1939 1968 1969 1997 1984 1978 2006 1946 1995 1988 2011 1961
 1977 1998 1962 1958 1985 1975 2013 2016 1976 1960 1951 1999 1989 1956
 1994 1973 2014 2002 1942 1936 1972 1982 1965 1935 1954 1987 1943 1934
 2009 1929 1957 1928 1931 1937 1927 1925 1926 1922 1924 1920 1921]


Column: number_of_marriages
['Married once', 'Married twice (or more)', 'Married thrice (or more)', 'Not Applicable']
Categories (4, object): ['Not Applicable' < 'Married once' < 'Married twice (or more)' < 'Married thrice (or more)']


Column: married_within_year
['Blank (No)', 'N/A', 'Yes']
Categories (3, object): ['N/A' < 'Blank (No)' < 'Yes']


Column: year_of_marriage
[1953 1994    0 1971 1975 2008 2012 2015 1956 2003 1967 2000 2004 2001
 2002 1990 1988 1969 1952 1950 1996 1973 1970 1993 1965 2007 1991 1982
 1997 2014 1981 2005 1962 1995 2009 2016 2013 1987 2011 2010 1963 1978
 1961 1989 1966 1983 1985 1974 1954 1968 1979 1958 1948 2006 1951 1955
 1999 1998 1980 1976 1949 1964 1986 1992 1960 1943 1957 1972 1977 1959
 1984 1946 1947 1939 1945 1940 1944 1942 1941 1938 1937 1936]


Column: fertility_year
['N/A', 'No', 'Yes']
Categories (3, object): ['N/A' < 'No' < 'Yes']


Column: race
['White', 'Black/African American/Negro', 'Two major races', 'Chinese', 'American Indian or Alaska Native', 'Other Asian or Pacific Islander', 'Other race, nec', 'Three or more major races', 'Japanese']
Categories (9, object): ['White' < 'Black/African American/Negro' < 'American Indian or Alaska Native' < 'Chinese' ... 'Other Asian or Pacific Islander' < 'Other race, nec' < 'Two major races' < 'Three or more major races']


Column: detailed_race
['White', 'Black/African American/Negro', 'White and Black', 'Chinese', 'Creek', ..., 'AIAN and Asian Indian', 'White, Chinese, Filipino, Hawaiian (2000 1%)', 'Comanche', 'Cheyenne', '   Bhutanese']
Length: 139
Categories (139, object): ['White' < 'Black/African American/Negro' < 'Apache' < 'Blackfoot' ... 'White, Black, AIAN, PI, other race write_in' < 'White, Black, Asian, PI, other race write_in' < 'Black, AIAN, Asian, PI, other race write_in' < 'White, Black, AIAN, Asian, PI, other race wri...]


Column: hispanic_origin
['Not Hispanic', 'Puerto Rican', 'Mexican', 'Other', 'Cuban']
Categories (5, object): ['Not Hispanic' < 'Mexican' < 'Puerto Rican' < 'Cuban' < 'Other']


Column: detailed_hispanic_origin
['Not Hispanic', 'Puerto Rican', 'Mexican', 'Guatemalan', 'Colombian', ..., 'Paraguayan', 'Chilean', 'South American, n.e.c.', 'Bolivian', 'Central American, n.e.c.']
Length: 24
Categories (24, object): ['Not Hispanic' < 'Mexican' < 'Puerto Rican' < 'Cuban' ... 'South American, n.e.c.' < 'Spaniard' < 'Dominican' < 'Other, n.s. ']


Column: birthplace
['Alabama', 'Georgia', 'Minnesota', 'Louisiana', 'Florida', ..., 'Sweden', 'Americas, n.s.', 'Albania', 'Latvia', 'Lithuania']
Length: 124
Categories (124, object): ['Alabama' < 'Alaska' < 'Arizona' < 'Arkansas' ... 'AFRICA' < 'Australia and New Zealand' < 'Pacific Islands' < 'Other n.e.c.']


Column: detailed_birthplace
['Alabama', 'Georgia', 'Minnesota', 'Louisiana', 'Florida', ..., 'Algeria', 'Zambia', 'Azerbaijan', 'Dominica', 'Antigua-Barbuda']
Length: 212
Categories (212, object): ['Alabama' < 'Alaska' < 'Arizona' < 'Arkansas' ... 'Marshall Islands' < 'Micronesia' < 'Northern Mariana Islands' < 'Other n.e.c.']


Column: first_ancestry
['United States', 'Not Reported', 'African-American', 'Irish, various subheads,', 'Hungarian', ..., 'Sierra Leonean', 'Fijian', 'North African', 'British Virgin Islander', 'Slavonian']
Length: 203
Categories (203, object): ['Alsatian, Alsace-Lorraine' < 'Austrian' < 'Basque' < 'Belgian' ... 'Mixture' < 'Uncodable' < 'Other' < 'Not Reported']


Column: detailed_first_ancestry
['United States', 'Not Reported', 'African-American (1990-2000, ACS, PRCS)', 'Irish', 'Hungarian', ..., 'Sierra Leonean', 'Fijian', 'North African', 'Antigua (1990-2000, ACS, PRCS)', 'Slavonian']
Length: 230
Categories (230, object): ['Alsatian' < 'Austrian' < 'Basque (1990-2000)' < 'Belgian' ... 'Uncodable' < 'Not Classified' < 'Other' < 'Not Reported']


Column: citizenship_status
['N/A', 'Naturalized citizen', 'Born abroad of American parents', 'Not a citizen']
Categories (4, object): ['N/A' < 'Born abroad of American parents' < 'Naturalized citizen' < 'Not a citizen']


Column: year_of_naturalization
['N/A', '1986', '1968', '2010', '1999', ..., '1943 (1943-44, 2012 ACS/PRCS)', '1940 (1940-1942, 2012 ACS/PRCS)', '1934 (1934-1939, 2012 ACS/PRCS)', '1945', '1951']
Length: 77
Categories (77, object): ['1928 (1928 or earlier, 2012 ACS/PRCS)' < '1929 (1929-1933, 2012 ACS/PRCS)' < '1934 (1934-1939, 2012 ACS/PRCS)' < '1940 (1940-1942, 2012 ACS/PRCS)' ... '2014' < '2015' < 2016 < 'N/A']


Column: year_of_immigration
[   0 1974 1965 1980 2000 2003 2007 1994 2006 2010 2013 2004 2014 2015
 2001 1983 1998 2002 2009 1951 1999 1979 1960 1976 1985 1993 1975 1978
 1989 1966 1967 2005 1986 1988 2008 1964 1959 1997 1958 1995 1962 1977
 2016 1987 2011 1984 1992 1961 1950 1971 1981 1969 2012 1963 1982 1973
 1953 1990 1946 1991 1972 1956 1957 1955 1996 1948 1970 1968 1952 1947
 1939 1954 1949 1945 1937 1940 1924 1926 1943 1935 1928 1932 1942 1941
 1930 1922 1921]


Column: years_in_usa
[ 0 42 51 36 16 13  9 22 10  6  3 12  2  1 15 33 18 14  7 65 17 37 56 40
 31 23 41 38 27 50 49 11 30 28  8 52 57 19 58 21 54 39 29  5 32 24 55 66
 45 35 47  4 53 34 43 63 26 70 25 44 60 59 61 20 68 46 48 64 69 77 62 67
 71 79 76 92 90 73 81 88 84 74 75 86 94 95]


Column: english_proficiency
['Yes, speaks only English', 'N/A (Blank)', 'Does not speak English', 'Yes, speaks very well', 'Yes, speaks well', 'Yes, but not well']
Categories (6, object): ['N/A (Blank)' < 'Does not speak English' < 'Yes, speaks only English' < 'Yes, speaks very well' < 'Yes, speaks well' < 'Yes, but not well']


Column: american_indian_race
['No', 'Yes']
Categories (2, object): ['No' < 'Yes']


Column: asian_race
['No', 'Yes']

In [3]:
import pandas as pd

# Define the categories and their respective terms
categories = {
    "Demographic": [
        "sex", "age", "year_of_birth", "race", "detailed_race", "hispanic_origin", "detailed_hispanic_origin",
        "birthplace", "detailed_birthplace", "first_ancestry", "detailed_first_ancestry", "citizenship_status",
        "year_of_naturalization", "year_of_immigration", "years_in_usa", "english_proficiency", "american_indian_race",
        "asian_race", "black_race", "pacific_islander_race", "white_race", "other_race"
    ],
    "Household": [
        "child_age_leq_4", "family_size", "number_of_children", "age_of_eldest_child", "age_of_youngest_child",
        "number_of_siblings", "parent_presence", "household_weight", "metropolitan_status", "us_census_region",
        "group_quarters_status"
    ],
    "Marital and Fertility": [
        "marital_status", "number_of_marriages", "married_within_year", "year_of_marriage", "fertility_year"
    ],
    "Education": [
        "school_attendance", "education", "detailed_education", "grade_attended", "detailed_grade_attended",
        "school_type", "degree_field", "detailed_degree_field", "second_degree_field", "detailed_second_degree_field",
        "education_score_1990"
    ],
    "Employment": [
        "employment_status", "detailed_employment_status", "labour_force_participation", "occupation",
        "occupation_1990_classification", "occupation_2010_classification", "industry", "industry_1990_classification",
        "class_of_worker", "detailed_class_of_worker", "soc_occupation", "naics_industry", "weeks_worked",
        "usual_hours_worked", "worked_last_year", "wage_income"
    ],
    "Survey Metadata": [
        "survey_year", "dataset_number", "household_serial_number", "person_number_within_household", "person_weight"
    ],
    "Veteran Status": [
        "veteran_status", "detailed_veteran_status"
    ]
}

# Reverse the dictionary to map terms to categories
term_to_category = {term: category for category, terms in categories.items() for term in terms}

# Load the CSV file
file_path = r'C:\Users\kappv\Desktop\Data-Analysis-with-LLM-5\experiment\data\corresult5.csv'
df = pd.read_csv(file_path, header=None)

# Add new columns for the categories
df['Category1'] = df[7].map(term_to_category)
df['Category2'] = df[8].map(term_to_category)

# Save the updated DataFrame to a new CSV file
output_path = r'C:\Users\kappv\Desktop\Data-Analysis-with-LLM-5\experiment\data\corresult5_updated.csv'
df.to_csv(output_path, index=False, header=False)